name: Build Jailex APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Force Fix Gradle Engine
        run: |
          rm -f gradlew
          curl -L https://raw.githubusercontent.com/gradle/gradle/master/gradlew -o gradlew
          chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload HUD App
        uses: actions/upload-artifact@v4
        with:
          name: Jailex-HUD-v1
          path: app/build/outputs/apk/debug/*.apk
